### PR TITLE
Update library to compile on upcoming 0.14.0 PS release

### PR DESCRIPTION
**Pull request by JordanMartinez**

### CODE REVIEW

**Comment by srghma** [comment]
@natefaubion could you merge this, please

**Comment by srghma** [comment]
@natefaubion 

with new changes to libs

how would you suggest to fix

```
[5/6 ModuleNotFound] .spago/routing-duplex/master/src/Routing/Duplex/Parser.purs:45:1

  45  import Global.Unsafe (unsafeDecodeURIComponent)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Global.Unsafe was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[6/6 ModuleNotFound] .spago/routing-duplex/master/src/Routing/Duplex/Printer.purs:18:1

  18  import Global.Unsafe (unsafeEncodeURIComponent)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  Module Global.Unsafe was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.
```

2021-02-05-22:02:54-screenshot

**Comment by natefaubion** [comment]
I think it's fine to depend on JSURI for now, since Globals was just as dodgy. I would like a "pure" implementation somewhere, but I think it's non-trivial.

**Comment by srghma** [comment]
> I would like a "pure" implementation somewhere, but I think it's non-trivial.

Don't understand

____

@natefaubion I mean should `parsePath` return `Maybe ...` or in this bimap we should use `unsafePartial fromJust`?

**Comment by thomashoneyman** [comment]
Thanks! This was fixed in #21.

**Pull request closed without merging**
